### ISSUE TITLE
博客评论更新 - A5耀日庄主的博客

### ISSUE THREAD

**Issue by SunbossRS** [SunbossRS/SunTalk_Save#34]
http://srsyrzz.ml/2018/09/05/BlogCommentEmoji.html 

 博客评论更新

**Comment by SunbossRS** [comment]
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/滑稽.png)
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/滑稽.png)
你们想干点什么

**Comment by tea9** [comment]
这是滑稽。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/滑稽.png)

这是开心。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/开心.png) 

这是流泪。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/流泪.png) 

这是吐血。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/吐血.png) 

这是酷霸(在表情里说的是装逼)。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/装b.png) 

这是疑问。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/疑问.png) 

这是流汗。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/流泪.png) 

这是伤心(沮丧脸)。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/伤心.png) 

这是笑哭。
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/笑哭.png)

**Comment by tea9** [comment]
![emoji](//github.com/sunbossrs/blogcommentstore/raw/master/emoji/滑稽.png)

**Comment by sctop** [comment]
In fact, if you are learned HTML5 in a short time, and you remember some things of HTML5 by now, you actually can use HTML code writing a post - not use Markdown. And HTML5 can let your picture and text in the same line.
事实上，如果您在短时间内学习HTML5，并且您现在还记得HTML5的一些内容，那么您实际上可以使用HTML代码编写帖子 - 而不是使用Markdown。 HTML5可以让你的图片和文字在同一行。

（没错我来秀英文了）

**Comment by SunbossRS** [comment]
> @sctop
> In fact, if you are learned HTML5 in a short time, and you remember some things of HTML5 by now, you actually can use HTML code writing a post - not use Markdown. And HTML5 can let your picture and text in the same line.
> 事实上，如果您在短时间内学习HTML5，并且您现在还记得HTML5的一些内容，那么您实际上可以使用HTML代码编写帖子 - 而不是使用Markdown。 HTML5可以让你的图片和文字在同一行。
> 
> （没错我来秀英文了）

so 是怎么样😊

**Comment by SunbossRS** [comment]
> @sctop
> In fact, if you are learned HTML5 in a short time, and you remember some things of HTML5 by now, you actually can use HTML code writing a post - not use Markdown. And HTML5 can let your picture and text in the same line.
> 事实上，如果您在短时间内学习HTML5，并且您现在还记得HTML5的一些内容，那么您实际上可以使用HTML代码编写帖子 - 而不是使用Markdown。 HTML5可以让你的图片和文字在同一行。
> 
> （没错我来秀英文了）

是这样嘛
<pre>
<p>要不然<img src="http://github.com/bligcommentstore/raw/master/emoji/滑稽.png" />你会怎么样</p>
</pre>

**Comment by yizibi** [comment]
![emoji](http://github.com/sunbossrs/blogcommentstore/raw/master/emoji/装b.png) 
这个就是 markdown 的语法
