### ISSUE TITLE
如何让你的博客/普通的网站结尾显示名言警句 - A5耀日庄主的博客

### ISSUE THREAD

**Issue by SunbossRS** [SunbossRS/SunTalk_Save#8]
https://sunbossrs.github.io/2018/06/27/HtmlFooterSentences.html 

 如何让你的博客/普通的网站结尾显示名言警句

**Comment by SunbossRS** [comment]
技术由api lwl12提供。

**Comment by yizibi** [comment]
你网页右下角那个滑动到顶部,并且有百分比那个怎么搞的,我下载下来源码,有一个b2t.html,还有一个js文件,然后在footer.html,里面加了b2t.html,好像没起作用,帮忙看下,什么原因,感谢!

**Comment by SunbossRS** [comment]
@yizibi  
这个有点麻烦......
